[build]
  functions = "functions"

[[redirects]]
  from = "/api/verify-code"
  to = "/.netlify/functions/verify-code"
  status = 200

[[redirects]]
  from = "/api/bilibili-videos"
  to = "/.netlify/functions/bilibili-videos"
  status = 200
